import type { DialogueLine, QuestionBundle, QuestionOption, ResponseNode } from "./types";

export const ABU_SAEED_GREETING: DialogueLine[] = [
  {
    characterId: "abuSaeed",
    text: "أهلاً وسهلاً يا أستاذ... نوّرت، اتفضل.",
    mood: "happy",
  },
  {
    characterId: "detective",
    text: "أهلاً بحضرتك يا أستاذ أبو سعيد.",
    mood: "neutral",
  },
  {
    characterId: "abuSaeed",
    text: "أستاذ منصور قالّي إنك هتيجي، وأنا بصراحة محتاج حد يقعد معايا ويفهمني الموضوع بهدوء.",
    mood: "concerned",
  },
];

export const QUESTION_OPTIONS: Record<string, QuestionOption> = {
  q1a: {
    id: "q1a",
    bundleId: "bundle_1_opening",
    text: "تمام يا أستاذ أبو سعيد، خلّيني أبدأ من عندك إنت. إيه أكتر حاجة شاغلاك أو مخلياك حاسس إن فيه حاجة محتاجة تتفهم دلوقتي في الشغل؟",
    quality: "strong",
    function: "claim_opening",
    responseId: "r1a",
    trustEffect: 1,
    recoveryCost: 0,
    knowledgeEffects: { claimOpened: true },
  },
  q1b: {
    id: "q1b",
    bundleId: "bundle_1_opening",
    text: "قبل ما ندخل في التفاصيل، الفترة دي بالنسبة لك تعتبر موسم مهم قد إيه؟ يعني عادة بتكون عامل عليها توقعات كبيرة؟",
    quality: "good",
    function: "context_opening",
    responseId: "r1b",
    trustEffect: 0,
    recoveryCost: 1,
    knowledgeEffects: { contextOpened: true },
  },
  q1c: {
    id: "q1c",
    bundleId: "bundle_1_opening",
    text: "حضرتك شايف إن السبب في الأسعار؟ ولا الناس بقت أقل في الشراء؟",
    quality: "weak",
    function: "weak_premature_hypothesis",
    responseId: "r1c",
    trustEffect: -1,
    recoveryCost: 1,
    knowledgeEffects: {},
  },

  q1r_a: {
    id: "q1r_a",
    bundleId: "bundle_1_recovery",
    text: "طيب وإيه اللي مخليك قلقان دلوقتي تحديدًا؟",
    quality: "strong",
    function: "claim_opening",
    responseId: "r1a",
    trustEffect: 1,
    recoveryCost: 0,
    knowledgeEffects: { claimOpened: true },
  },
  q1r_b: {
    id: "q1r_b",
    bundleId: "bundle_1_recovery",
    text: "يعني شايف الموسم ماشي إزاي لحد دلوقتي؟",
    quality: "good",
    function: "context_opening",
    responseId: "r1b",
    trustEffect: 0,
    recoveryCost: 0,
    knowledgeEffects: { contextOpened: true },
  },
  q1r_c: {
    id: "q1r_c",
    bundleId: "bundle_1_recovery",
    text: "حاسس السبب في الأسعار؟",
    quality: "weak",
    function: "weak_premature_hypothesis",
    responseId: "r1c",
    trustEffect: -1,
    recoveryCost: 0,
    knowledgeEffects: {},
  },

  q2a: {
    id: "q2a",
    bundleId: "bundle_2_claim_definition",
    text: "لما بتقول إن الموسم أقل من اللي كنت متوقعه، عايز أفهمها منك بدقة: إيه اللي إنت شايفه ومخليك تقول كده؟ يعني أقل في إيه تحديدًا؟",
    quality: "strong",
    function: "claim_definition",
    responseId: "r2a",
    trustEffect: 1,
    recoveryCost: 0,
    knowledgeEffects: { claimDefined: true },
  },
  q2b: {
    id: "q2b",
    bundleId: "bundle_2_claim_definition",
    text: "إنت اللي مضايقك أكتر دلوقتي إن الحركة نفسها قليلة؟ ولا إن الحركة موجودة بس الرقم النهائي أقل من اللي كنت منتظره؟",
    quality: "good",
    function: "symptom_structure",
    responseId: "r2b",
    trustEffect: 0,
    recoveryCost: 1,
    knowledgeEffects: {},
  },
  q2c: {
    id: "q2c",
    bundleId: "bundle_2_claim_definition",
    text: "يعني الناس داخلة تتفرج ومش بتشتري كفاية؟",
    quality: "weak",
    function: "weak_premature_hypothesis",
    responseId: "r2c",
    trustEffect: -1,
    recoveryCost: 1,
    knowledgeEffects: {},
  },

  q2r_a: {
    id: "q2r_a",
    bundleId: "bundle_2_recovery",
    text: "لما تقول أقل من المتوقع، تقصد أقل في إيه تحديدًا؟",
    quality: "strong",
    function: "claim_definition",
    responseId: "r2a",
    trustEffect: 1,
    recoveryCost: 0,
    knowledgeEffects: { claimDefined: true },
  },
  q2r_b: {
    id: "q2r_b",
    bundleId: "bundle_2_recovery",
    text: "يعني الرقم النهائي هو اللي مضايقك أكتر؟",
    quality: "good",
    function: "symptom_structure",
    responseId: "r2b",
    trustEffect: 0,
    recoveryCost: 0,
    knowledgeEffects: {},
  },
  q2r_c: {
    id: "q2r_c",
    bundleId: "bundle_2_recovery",
    text: "حاسس الناس مش بتشتري؟",
    quality: "weak",
    function: "weak_premature_hypothesis",
    responseId: "r2c",
    trustEffect: -1,
    recoveryCost: 0,
    knowledgeEffects: {},
  },

  q3a: {
    id: "q3a",
    bundleId: "bundle_3_request_bias",
    text: "طيب لما شفت الوضع بالشكل ده، كان أول تصرف جه في بالك تعمل إيه؟ يعني لو ما كناش قاعدين دلوقتي، كنت غالبًا هتميل لإيه عشان تتعامل مع اللي شايفه؟",
    quality: "strong",
    function: "request_extraction",
    responseId: "r3a",
    trustEffect: 1,
    recoveryCost: 0,
    knowledgeEffects: { requestKnown: true },
  },
  q3b: {
    id: "q3b",
    bundleId: "bundle_3_request_bias",
    text: "اللي مخليك شايل هم الموضوع أكتر، إن الرقم أقل وبس؟ ولا لأن الفترة دي بالنسبة لك لازم تطلع بنتيجة معينة؟",
    quality: "good",
    function: "stakes_extraction",
    responseId: "r3b",
    trustEffect: 0,
    recoveryCost: 1,
    knowledgeEffects: { stakesKnown: true },
  },
  q3c: {
    id: "q3c",
    bundleId: "bundle_3_request_bias",
    text: "طب ما نجرب عروض فعلًا ونشوف لو ده هيحرك الدنيا؟",
    quality: "weak",
    function: "solution_jump",
    responseId: "r3c",
    trustEffect: -1,
    recoveryCost: 1,
    knowledgeEffects: {},
  },

  q3r_a: {
    id: "q3r_a",
    bundleId: "bundle_3_recovery",
    text: "لو ما كناش قاعدين دلوقتي، كنت هتميل تعمل إيه غالبًا؟",
    quality: "strong",
    function: "request_extraction",
    responseId: "r3a",
    trustEffect: 1,
    recoveryCost: 0,
    knowledgeEffects: { requestKnown: true },
  },
  q3r_b: {
    id: "q3r_b",
    bundleId: "bundle_3_recovery",
    text: "إيه أكتر حاجة مقلقاك لو الوضع فضل كده؟",
    quality: "good",
    function: "stakes_extraction",
    responseId: "r3b",
    trustEffect: 0,
    recoveryCost: 0,
    knowledgeEffects: { stakesKnown: true },
  },
  q3r_c: {
    id: "q3r_c",
    bundleId: "bundle_3_recovery",
    text: "نبدأ عروض؟",
    quality: "weak",
    function: "solution_jump",
    responseId: "r3c",
    trustEffect: -1,
    recoveryCost: 0,
    knowledgeEffects: {},
  },

  q4a: {
    id: "q4a",
    bundleId: "bundle_4_baseline",
    text: "خلّيني أمسك الحتة دي بوضوح... إنت بتقول أقل من المتوقع، طيب التوقع ده جاي منين؟ يعني وإنت بتحكم إن الرقم أقل، بتقارن على إيه بالضبط؟",
    quality: "strong",
    function: "baseline_identification",
    responseId: "r4a",
    trustEffect: 1,
    recoveryCost: 0,
    knowledgeEffects: { baselineKnown: true },
  },
  q4b: {
    id: "q4b",
    bundleId: "bundle_4_baseline",
    text: "عايز أتأكد من حاجة... القلق اللي عندك ده جاي من اتجاه واضح شايفه بيتكرر، ولا جاي أكتر من مقارنة الفترة دي بفترة معينة وإحساسك إن المفروض تبقى أعلى؟",
    quality: "good",
    function: "comparison_vs_trend",
    responseId: "r4b",
    trustEffect: 0,
    recoveryCost: 1,
    knowledgeEffects: { comparisonBasedConcern: true },
  },
  q4c: {
    id: "q4c",
    bundleId: "bundle_4_baseline",
    text: "هل في قسم معيّن هو اللي واقع ومسبب الفرق ده؟",
    quality: "weak",
    function: "weak_premature_hypothesis",
    responseId: "r4c",
    trustEffect: -1,
    recoveryCost: 1,
    knowledgeEffects: {},
  },

  q4r_a: {
    id: "q4r_a",
    bundleId: "bundle_4_recovery",
    text: "طيب المقارنة دي تحديدًا جاية منين؟",
    quality: "strong",
    function: "baseline_identification",
    responseId: "r4a",
    trustEffect: 1,
    recoveryCost: 0,
    knowledgeEffects: { baselineKnown: true },
  },
  q4r_b: {
    id: "q4r_b",
    bundleId: "bundle_4_recovery",
    text: "إنت بتقيس على فترة معيّنة ولا على إحساس عام؟",
    quality: "good",
    function: "comparison_vs_trend",
    responseId: "r4b",
    trustEffect: 0,
    recoveryCost: 0,
    knowledgeEffects: { comparisonBasedConcern: true },
  },
  q4r_c: {
    id: "q4r_c",
    bundleId: "bundle_4_recovery",
    text: "هل في جزء معيّن هو السبب؟",
    quality: "weak",
    function: "weak_premature_hypothesis",
    responseId: "r4c",
    trustEffect: -1,
    recoveryCost: 0,
    knowledgeEffects: {},
  },

  q5a: {
    id: "q5a",
    bundleId: "bundle_5_reality_check",
    text: "طيب لو شلنا السنة اللي فاتت من الصورة للحظة، ووقفنا قدام اللي حاصل دلوقتي زي ما هو... إنت شايف إيه بعينك في المحل؟ يعني الحركة أهدى فعلًا؟ ولا الناس موجودة، لكن اللي مخليك قلقان هو إن الرقم لما يتقارن يطلع أقل؟",
    quality: "strong",
    function: "reality_check",
    responseId: "r5a",
    trustEffect: 1,
    recoveryCost: 0,
    knowledgeEffects: { realityChecked: true },
  },
  q5b: {
    id: "q5b",
    bundleId: "bundle_5_reality_check",
    text: "من اللي حضرتك شايفه قدامك، في حاجة واضحة جدًا في سلوك الزباين أو الحركة تقول إن الدنيا واقعة؟ ولا الإحساس بالمشكلة جاي أكتر لما تبص على الأرقام مقارنة بغيرها؟",
    quality: "good",
    function: "reality_check",
    responseId: "r5b",
    trustEffect: 0,
    recoveryCost: 1,
    knowledgeEffects: {},
  },
  q5c: {
    id: "q5c",
    bundleId: "bundle_5_reality_check",
    text: "هل الموظفين محتاجين يبقوا أنشط شوية في البيع؟",
    quality: "weak",
    function: "weak_premature_hypothesis",
    responseId: "r5c",
    trustEffect: -1,
    recoveryCost: 1,
    knowledgeEffects: {},
  },

  q5r_a: {
    id: "q5r_a",
    bundleId: "bundle_5_recovery",
    text: "يعني القلق جاي من المقارنة أكتر من اللي شايفه بعينك؟",
    quality: "strong",
    function: "reality_check",
    responseId: "r5a",
    trustEffect: 1,
    recoveryCost: 0,
    knowledgeEffects: { realityChecked: true },
  },
  q5r_b: {
    id: "q5r_b",
    bundleId: "bundle_5_recovery",
    text: "الحركة موجودة بس الرقم هو اللي مضايقك أكتر؟",
    quality: "good",
    function: "reality_check",
    responseId: "r5b",
    trustEffect: 0,
    recoveryCost: 0,
    knowledgeEffects: {},
  },
  q5r_c: {
    id: "q5r_c",
    bundleId: "bundle_5_recovery",
    text: "المشكلة من الناس عندك؟",
    quality: "weak",
    function: "weak_premature_hypothesis",
    responseId: "r5c",
    trustEffect: -1,
    recoveryCost: 0,
    knowledgeEffects: {},
  },

  q6a: {
    id: "q6a",
    bundleId: "bundle_6_baseline_validity",
    text: "طيب اسمحلي أسألك السؤال ده بصراحة... السنة اللي فاتت اللي إنت واخدها مرجع، كانت سنة عادية بالنسبة لك فعلًا؟ ولا كان فيها أي ظروف مختلفة خلت نتيجتها أعلى من المعتاد؟",
    quality: "strong",
    function: "baseline_validity",
    responseId: "r6a",
    trustEffect: 1,
    recoveryCost: 0,
    knowledgeEffects: { baselineQuestioned: true },
  },
  q6b: {
    id: "q6b",
    bundleId: "bundle_6_baseline_validity",
    text: "إنت دايمًا بتحكم على المواسم مقارنة بالسنة اللي قبلها بس؟ ولا في العادي بتبص على أكتر من سنة عشان تعرف الطبيعي الحقيقي للمحل؟",
    quality: "good",
    function: "comparison_method",
    responseId: "r6b",
    trustEffect: 0,
    recoveryCost: 1,
    knowledgeEffects: { comparisonMethodWeak: true },
  },
  q6c: {
    id: "q6c",
    bundleId: "bundle_6_baseline_validity",
    text: "هل المنافسة زادت السنة دي وده اللي مأثر على البيع؟",
    quality: "weak",
    function: "weak_premature_hypothesis",
    responseId: "r6c",
    trustEffect: -1,
    recoveryCost: 1,
    knowledgeEffects: {},
  },

  q6r_a: {
    id: "q6r_a",
    bundleId: "bundle_6_recovery",
    text: "يعني ممكن المرجع نفسه ما يكونش عادي؟",
    quality: "strong",
    function: "baseline_validity",
    responseId: "r6a",
    trustEffect: 1,
    recoveryCost: 0,
    knowledgeEffects: { baselineQuestioned: true },
  },
  q6r_b: {
    id: "q6r_b",
    bundleId: "bundle_6_recovery",
    text: "هل السنة اللي فاتت تمثل الطبيعي فعلًا؟",
    quality: "good",
    function: "comparison_method",
    responseId: "r6b",
    trustEffect: 0,
    recoveryCost: 0,
    knowledgeEffects: { comparisonMethodWeak: true },
  },
  q6r_c: {
    id: "q6r_c",
    bundleId: "bundle_6_recovery",
    text: "المنافسين مأثرين؟",
    quality: "weak",
    function: "weak_premature_hypothesis",
    responseId: "r6c",
    trustEffect: -1,
    recoveryCost: 0,
    knowledgeEffects: {},
  },

  q7a: {
    id: "q7a",
    bundleId: "bundle_7_exceptional_factor",
    text: "إيه اللي كان مختلف وقتها عن الطبيعي؟ يعني لو رجعنا للسنة اللي فاتت، إيه العوامل اللي خلتها أحسن من المعتاد في رأيك؟",
    quality: "strong",
    function: "exceptional_factor",
    responseId: "r7a",
    trustEffect: 1,
    recoveryCost: 0,
    knowledgeEffects: { exceptionalYearKnown: true },
  },
  q7b: {
    id: "q7b",
    bundleId: "bundle_7_exceptional_factor",
    text: "ولو بصّينا قبل السنة اللي فاتت كمان، المواسم العادية كانت أقرب للي حاصل دلوقتي؟ ولا أقرب للسنة اللي فاتت؟",
    quality: "good",
    function: "exceptional_factor",
    responseId: "r7b",
    trustEffect: 0,
    recoveryCost: 1,
    knowledgeEffects: { exceptionalYearKnown: true },
  },
  q7c: {
    id: "q7c",
    bundleId: "bundle_7_exceptional_factor",
    text: "طب نعمل عروض بسيطة ونشوف بعدها؟",
    quality: "weak",
    function: "solution_jump",
    responseId: "r7c",
    trustEffect: -1,
    recoveryCost: 1,
    knowledgeEffects: {},
  },

  q7r_a: {
    id: "q7r_a",
    bundleId: "bundle_7_recovery",
    text: "يعني السنة اللي فاتت كانت أعلى من الطبيعي؟",
    quality: "strong",
    function: "exceptional_factor",
    responseId: "r7a",
    trustEffect: 1,
    recoveryCost: 0,
    knowledgeEffects: { exceptionalYearKnown: true },
  },
  q7r_b: {
    id: "q7r_b",
    bundleId: "bundle_7_recovery",
    text: "في حاجة كانت مميزة وقتها؟",
    quality: "good",
    function: "exceptional_factor",
    responseId: "r7b",
    trustEffect: 0,
    recoveryCost: 0,
    knowledgeEffects: { exceptionalYearKnown: true },
  },
  q7r_c: {
    id: "q7r_c",
    bundleId: "bundle_7_recovery",
    text: "طب نتحرك بعروض؟",
    quality: "weak",
    function: "solution_jump",
    responseId: "r7c",
    trustEffect: -1,
    recoveryCost: 0,
    knowledgeEffects: {},
  },

  q7a_followup: {
    id: "q7a_followup",
    bundleId: "bundle_7a_followup",
    text: "والزحمة الزيادة دي كانت جاية من إيه تحديدًا؟ كان في حاجة حصلت وقتها خلت المنطقة كلها أنشط من العادي؟",
    quality: "strong",
    function: "exceptional_cause_followup",
    responseId: "r7a_followup",
    trustEffect: 1,
    recoveryCost: 0,
    knowledgeEffects: { exceptionalCauseKnown: true },
  },
};

export const RESPONSES: Record<string, ResponseNode> = {
  r1a: {
    id: "r1a",
    text: "بص يا أستاذ... أنا حاسس إن الموسم ده أهدى من اللي كنت عامله حسابي. يعني الرقم مش مريحني، وحاسس إن فيه حاجة أقل من اللي كنت مستنيه.",
    tone: "warm",
    noteCandidateIds: ["note_claim_opened"],
  },
  r1b: {
    id: "r1b",
    text: "أيوه طبعًا، الفترة دي مهمة. وبيبقى الواحد داخلها وهو متوقع نتيجة أحسن من كده.",
    tone: "warm",
    noteCandidateIds: ["note_context_season_important"],
  },
  r1c: {
    id: "r1c",
    text: "أنا لسه مش قادر أحدد كده... عشان كده أصلًا كنت عايز حد يساعدني أفهم.",
    tone: "guarded",
    noteCandidateIds: ["note_weak_price_guess"],
  },

  r2a: {
    id: "r2a",
    text: "يعني لما أبص على رقم البيع في الفترة دي، بلاقيه أهدى من اللي كنت مستنيه. المحل شغال، بس الرقم النهائي مش على قد اللي كنت عامل حسابي عليه.",
    tone: "warm",
    noteCandidateIds: ["note_claim_defined"],
  },
  r2b: {
    id: "r2b",
    text: "لا، هو ده اللي محيرني... الحركة مش مختفية، بس الرقم النهائي هو اللي مش مريحني.",
    tone: "reflective",
    noteCandidateIds: ["note_claim_defined"],
  },
  r2c: {
    id: "r2c",
    text: "ممكن يكون فيه جزء من كده، بس أنا ماقدرش أقول ده بثقة.",
    tone: "guarded",
    noteCandidateIds: ["note_weak_opinion_missing_purchase"],
  },

  r3a: {
    id: "r3a",
    text: "أنا بصراحة أول حاجة جت في دماغي إني أعمل عروض أو أخفض شوية. قلت يمكن ده يحرك البيع أكتر.",
    tone: "warm",
    noteCandidateIds: ["note_request_discounts"],
  },
  r3b: {
    id: "r3b",
    text: "لأن الفترة دي مهمة، وأنا داخلها بتوقعات أعلى. فلما الرقم يطلع أهدى من اللي أنا عامله حسابي، بقلق.",
    tone: "warm",
    noteCandidateIds: ["note_stakes_high_expectation"],
  },
  r3c: {
    id: "r3c",
    text: "ما هو ده اللي أنا كنت بفكر فيه، بس قبل ما أعمل كده كنت عايز أفهم الأول.",
    tone: "guarded",
    noteCandidateIds: ["note_solution_jump"],
  },

  r4a: {
    id: "r4a",
    text: "أنا ببص على نفس الفترة من السنة اللي فاتت. السنة اللي فاتت في نفس الوقت الرقم كان أعلى، فعشان كده حاسس إننا أقل.",
    tone: "warm",
    noteCandidateIds: ["note_baseline_last_year"],
  },
  r4b: {
    id: "r4b",
    text: "هو بصراحة جاي أكتر من المقارنة بالفترة دي في السنة اللي فاتت. يعني مش علشان شايف سقوط مستمر، لأ... بس المقارنة هي اللي مقلقاني.",
    tone: "reflective",
    noteCandidateIds: ["note_comparison_not_trend"],
  },
  r4c: {
    id: "r4c",
    text: "أنا دلوقتي اللي مضايقني الرقم العام، مش قادر أمسكه من جوّه لسه.",
    tone: "guarded",
    noteCandidateIds: ["note_weak_staff_guess"],
  },

  r5a: {
    id: "r5a",
    text: "لا، هو ده اللي محيرني... الناس موجودة، والحركة مش مختفية، وأنا مش شايف إن المحل واقع. بس أول ما أبص على الرقم مقارنة بالسنة اللي فاتت، أحس إننا أقل.",
    tone: "reflective",
    noteCandidateIds: ["note_reality_not_collapsing"],
  },
  r5b: {
    id: "r5b",
    text: "بصراحة لا، ما عنديش مشهد واضح يقول إن الدنيا واقعة. هو اللي مخليني قلقان أكتر هو المقارنة.",
    tone: "reflective",
    noteCandidateIds: ["note_reality_not_collapsing"],
  },
  r5c: {
    id: "r5c",
    text: "أنا مش شايف إن المشكلة واضحة من الناس عندي... ومش عايز أظلم حد وأنا لسه مش فاهم.",
    tone: "guarded",
    noteCandidateIds: ["note_weak_staff_guess"],
  },

  r6a: {
    id: "r6a",
    text: "بص... لما أفكر فيها كويس، لأ، مش أقدر أقول إنها كانت سنة عادية تمامًا. كان في عوامل مخلياها أحسن شوية من الطبيعي، بس أنا وقتها ما وقفتش مع الموضوع بالطريقة دي.",
    tone: "reflective",
    noteCandidateIds: ["note_baseline_not_normal"],
  },
  r6b: {
    id: "r6b",
    text: "بصراحة أنا غالبًا ببص على السنة اللي قبلها، وما بفتحش الصورة على أكتر من كده إلا نادر.",
    tone: "reflective",
    noteCandidateIds: ["note_comparison_method_weak"],
  },
  r6c: {
    id: "r6c",
    text: "المنافسة موجودة طبعًا، بس دي حاجة موجودة أصلًا... مش حاسس إنها تفسر اللي أنا قلقان منه بالشكل ده.",
    tone: "guarded",
    noteCandidateIds: ["note_weak_competition_guess"],
  },

  r7a: {
    id: "r7a",
    text: "كان في وقتها زحمة زيادة في المنطقة بشكل واضح، والدنيا كانت ماشية أحسن من العادي. يعني لو بصيت لها دلوقتي، لأ... هي ما كانتش سنة تمثل الوضع الطبيعي قوي.",
    tone: "reflective",
    noteCandidateIds: ["note_exceptional_year"],
  },
  r7b: {
    id: "r7b",
    text: "لا، بصراحة لو هاقارن بسنين عادية، اللي حاصل دلوقتي أقرب لهم أكتر من السنة اللي فاتت.",
    tone: "reflective",
    noteCandidateIds: ["note_exceptional_year"],
  },
  r7c: {
    id: "r7c",
    text: "بس لو أصل المقارنة نفسها مش سليمة، أبقى كده باخد قرار قبل ما أفهم... وده اللي أنا كنت خايف منه.",
    tone: "reflective",
    noteCandidateIds: ["note_solution_jump"],
  },

  r7a_followup: {
    id: "r7a_followup",
    text: "أيوه... وقتها كان في افتتاح كبير قريب من هنا، والمنطقة كلها كانت واخدة زخم مختلف. إحنا استفدنا من الحركة دي بشكل واضح.",
    tone: "reflective",
    noteCandidateIds: ["note_exceptional_cause"],
  },
};

export const QUESTION_BUNDLES: Record<string, QuestionBundle> = {
  bundle_1_opening: {
    id: "bundle_1_opening",
    stateTarget: "claim_opening",
    purpose: "فتح المشكلة المعلنة",
    isRecovery: false,
    optionIds: ["q1a", "q1b", "q1c"],
  },
  bundle_1_recovery: {
    id: "bundle_1_recovery",
    stateTarget: "claim_opening",
    purpose: "استكمال فتح المشكلة",
    isRecovery: true,
    optionIds: ["q1r_a", "q1r_b", "q1r_c"],
  },
  bundle_2_claim_definition: {
    id: "bundle_2_claim_definition",
    stateTarget: "claim_definition",
    purpose: "تثبيت claim",
    isRecovery: false,
    optionIds: ["q2a", "q2b", "q2c"],
    unlockConditions: ["claimOpened"],
  },
  bundle_2_recovery: {
    id: "bundle_2_recovery",
    stateTarget: "claim_definition",
    purpose: "استكمال تثبيت المشكلة",
    isRecovery: true,
    optionIds: ["q2r_a", "q2r_b", "q2r_c"],
    unlockConditions: ["claimOpened"],
  },
  bundle_3_request_bias: {
    id: "bundle_3_request_bias",
    stateTarget: "request_bias",
    purpose: "كشف الحل الذي يميل له العميل",
    isRecovery: false,
    optionIds: ["q3a", "q3b", "q3c"],
    unlockConditions: ["claimDefined"],
  },
  bundle_3_recovery: {
    id: "bundle_3_recovery",
    stateTarget: "request_bias",
    purpose: "استكمال فصل المشكلة عن الحل",
    isRecovery: true,
    optionIds: ["q3r_a", "q3r_b", "q3r_c"],
    unlockConditions: ["claimDefined"],
  },
  bundle_4_baseline: {
    id: "bundle_4_baseline",
    stateTarget: "baseline_identification",
    purpose: "تثبيت baseline",
    isRecovery: false,
    optionIds: ["q4a", "q4b", "q4c"],
    unlockConditions: ["claimDefined"],
  },
  bundle_4_recovery: {
    id: "bundle_4_recovery",
    stateTarget: "baseline_identification",
    purpose: "استكمال تثبيت baseline",
    isRecovery: true,
    optionIds: ["q4r_a", "q4r_b", "q4r_c"],
    unlockConditions: ["claimDefined"],
  },
  bundle_5_reality_check: {
    id: "bundle_5_reality_check",
    stateTarget: "reality_check",
    purpose: "فصل الواقع الحالي عن المقارنة",
    isRecovery: false,
    optionIds: ["q5a", "q5b", "q5c"],
    unlockConditions: ["baselineKnown"],
  },
  bundle_5_recovery: {
    id: "bundle_5_recovery",
    stateTarget: "reality_check",
    purpose: "استكمال reality check",
    isRecovery: true,
    optionIds: ["q5r_a", "q5r_b", "q5r_c"],
    unlockConditions: ["baselineKnown"],
  },
  bundle_6_baseline_validity: {
    id: "bundle_6_baseline_validity",
    stateTarget: "baseline_validity",
    purpose: "اختبار صلاحية المرجع",
    isRecovery: false,
    optionIds: ["q6a", "q6b", "q6c"],
    unlockConditions: ["baselineKnown", "realityChecked"],
  },
  bundle_6_recovery: {
    id: "bundle_6_recovery",
    stateTarget: "baseline_validity",
    purpose: "استكمال التشكيك في المرجع",
    isRecovery: true,
    optionIds: ["q6r_a", "q6r_b", "q6r_c"],
    unlockConditions: ["baselineKnown", "realityChecked"],
  },
  bundle_7_exceptional_factor: {
    id: "bundle_7_exceptional_factor",
    stateTarget: "exceptional_factor",
    purpose: "كشف أن السنة الماضية استثنائية",
    isRecovery: false,
    optionIds: ["q7a", "q7b", "q7c"],
    unlockConditions: ["baselineQuestioned"],
  },
  bundle_7_recovery: {
    id: "bundle_7_recovery",
    stateTarget: "exceptional_factor",
    purpose: "استكمال كشف الاستثنائية",
    isRecovery: true,
    optionIds: ["q7r_a", "q7r_b", "q7r_c"],
    unlockConditions: ["baselineQuestioned"],
  },
  bundle_7a_followup: {
    id: "bundle_7a_followup",
    stateTarget: "exceptional_cause",
    purpose: "كشف السبب الخارجي المحدد",
    isRecovery: false,
    optionIds: ["q7a_followup"],
    unlockConditions: ["exceptionalYearKnown"],
  },
};
